version: 2.1

orbs:
  node: cloudify/public-unittest-orb@1 #orb version
  wagonorb: cloudify/wagon-bulder-orb@1 #orb version
  releaseorb: cloudify/release-orb@1 #orb version
  managerorb: cloudify/manager-orb@1

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:

  py36:
    docker:
      - image: circleci/python:3.6

  cloudify-machine-py3:
    machine:
      image: ubuntu-1604:201903-01

commands:

  validate_examples:
    steps:
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip --user
      - run: |
          for p in `git log -1 --name-only --oneline | grep yaml | grep -v .circleci`
          do
              ecosystem-test validate-blueprint -b $p
          done

  validate_examples_nightlies:
    steps:
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip --user
      - run: |
          for d in `cat .cicd/supported_examples.json  | jq -r 'to_entries[] | .key'`
          do
              for f in `cat .cicd/supported_examples.json  | jq -r --arg keyvar "$d" '.[$keyvar][]'`
              do
                  ecosystem-test validate-blueprint -b $d/$f
              done
          done


  test_examples:
    steps:
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - run: pytest -s .cicd/test_examples.py -k 'test_getting_started'
      - run: docker cp virtual-machine/. cfy_manager:/tmp/virtual-machine
      - run: docker exec cfy_manager cfy blueprints upload /tmp/virtual-machine/$IAAS.yaml -b infra-$IAAS
      - run: ecosystem-test local-blueprint-test -b getting-started/mc-jboss.yaml -i infra_name=$IAAS -i infra_exists=true -i env_name=$CIRCLE_BUILD_NUM --test-id=bluex-gsmc-jboss-$IAAS-$CIRCLE_BUILD_NUM
      - run: ecosystem-test local-blueprint-test -b getting-started/mc-nodejs.yaml -i infra_name=$IAAS -i infra_exists=true -i env_name=$CIRCLE_BUILD_NUM --test-id=bluex-gsmc-nodejs-$IAAS-$CIRCLE_BUILD_NUM
      - run: ecosystem-test local-blueprint-test -b getting-started/mc-localstack.yaml -i infra_name=$IAAS -i infra_exists=true -i env_name=$CIRCLE_BUILD_NUM --test-id=bluex-gsmc-localstack-$IAAS-$CIRCLE_BUILD_NUM

  release_examples:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - attach_workspace:
          at: workspace
      - run:
          name: update pip
          command: pip install -U pip===20.3.3
      - run:
          name: install cloudify
          command: pip install -U cloudify==5.1 pytest==4.6.3
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip --user
      - run: python .cicd/package_examples.py

jobs:

  blueprints-validation:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - validate_examples

  blueprints-validation-nightlies:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - validate_examples_nightlies

  getting-started-aws:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: aws
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - test_examples

  getting-started-aws-terraform:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: aws-terraform
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - test_examples

  getting-started-aws-cloudformation:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: aws-cloudformation
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - test_examples

  getting-started-azure:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: azure
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - test_examples

  getting-started-azure-arm:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: azure
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - test_examples

  getting-started-gcp:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: gcp
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - test_examples

  release:
    executor: py36
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - release_examples

workflows:
  version: 2
  tests:
    jobs:
      - blueprints-validation
      - getting-started-aws:
          requires:
            - blueprints-validation
          filters:
            branches:
              only: master
      - getting-started-aws-terraform:
          requires:
            - getting-started-aws
          filters:
            branches:
              only: master
      - getting-started-aws-cloudformation:
          requires:
            - getting-started-aws-terraform
          filters:
            branches:
              only: master
      - getting-started-azure:
          requires:
            - getting-started-gcp
            - blueprints-validation
          filters:
            branches:
              only: master
      - getting-started-azure-arm:
          requires:
            - getting-started-azure
            - blueprints-validation
          filters:
            branches:
              only: master
      - getting-started-gcp:
          requires:
            - blueprints-validation
          filters:
            branches:
              only: master
      - release:
          requires:
            - blueprints-validation
            - getting-started-aws
            - getting-started-aws-cloudformation
            - getting-started-aws-terraform
            - getting-started-azure
            - getting-started-azure-arm
            - getting-started-gcp
          filters:
            branches:
              only: master
  nightly:
    triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - blueprints-validation-nightlies
      - getting-started-aws:
          requires:
            - blueprints-validation-nightlies
          filters:
            branches:
              only: master
      - getting-started-aws-terraform:
          requires:
            - getting-started-aws
          filters:
            branches:
              only: master
      - getting-started-aws-cloudformation:
          requires:
            - getting-started-aws-terraform
          filters:
            branches:
              only: master
      - getting-started-azure:
          requires:
            - blueprints-validation-nightlies
          filters:
            branches:
              only: master
      - getting-started-azure-arm:
          requires:
            - getting-started-azure
          filters:
            branches:
              only: master
      - getting-started-gcp:
          requires:
            - blueprints-validation-nightlies
          filters:
            branches:
              only: master

